---
- name: Configure WSL Ubuntu 26.04 LTS Environment
  hosts: my_desktop
  become: true
  roles:
    - { role: system, tags: ["system_only"] }

- name: User Environment Configuration
  hosts: my_desktop
  become: false
  roles:
    - { role: user, tags: ["user_only"] }
