---
- name: Set zsh shell
  ansible.builtin.set_fact:
    user_shell_executable: /bin/zsh

- name: Include Vim settings
  ansible.builtin.include_tasks: vim_setup.yml

- name: Include Zsh settings
  ansible.builtin.include_tasks: zsh_setup.yml

- name: Include installation of local user packages
  ansible.builtin.include_tasks: install_local_packages.yml

- name: Include configuration of user
  ansible.builtin.include_tasks: configure_user.yml
