---
- name: Install Zsh and Git
  ansible.builtin.apt:
    name: [zsh]
    state: present
  become: true

- name: Install Oh My Zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
  become: true
  become_user: "{{ ansible_user_id }}"

- name: Download Zsh Plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
    version: master
    update: false
  become: true
  become_user: "{{ ansible_user_id }}"
  loop:
    - name: "zsh-autosuggestions"
      repo: "https://github.com/zsh-users/zsh-autosuggestions"
    - name: "zsh-syntax-highlighting"
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"

- name: Set Zsh Theme to 'macovsky-ruby'
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: "^ZSH_THEME="
    line: 'ZSH_THEME="macovsky-ruby"'

- name: Configure .zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: "^plugins="
    line: "plugins=(git zsh-autosuggestions zsh-syntax-highlighting)"

- name: Add time to macovsky-ruby theme
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'PROMPT="[%D{% raw %}{%H:%M:%S}{% endraw %}] $PROMPT"'
    insertafter: EOF

- name: Add .local/bin to PATH in .zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    state: present
    create: true
    mode: "0644"

- name: Set Default Shell to Zsh for current user
  ansible.builtin.user:
    name: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    shell: /bin/zsh
  become: true

- name: Create custom zsh completion directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.zsh/completion"
    state: directory
    mode: '0755'

- name: Download Docker zsh completion script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker
    dest: "{{ ansible_env.HOME }}/.zsh/completion/_docker"
    mode: '0644'

- name: Add Docker completion path to .zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'fpath=({{ ansible_env.HOME }}/.zsh/completion $fpath)'
    insertbefore: "^source \\$ZSH/oh-my-zsh.sh"