---
- name: Check if the system is WSL
  ansible.builtin.set_fact:
    is_wsl: "{{ 'microsoft' in ansible_kernel }}"

- name: Notify WSL environment detection
  ansible.builtin.debug:
    msg: "WSL environment detected."
  when: is_wsl

- name: Check current timezone
  ansible.builtin.command: timedatectl show --property=Timezone --value
  register: current_tz
  changed_when: false

- name: Set timezone to Asia/Seoul
  ansible.builtin.command: timedatectl set-timezone Asia/Seoul
  when: current_tz.stdout != 'Asia/Seoul'
  changed_when: true

- name: Set hostname if custom name provided
  ansible.builtin.hostname:
    name: "{{ custom_hostname }}"
  when: custom_hostname is defined